### ISSUE TITLE
Ball goes through surfaces

### ISSUE THREAD

**Issue by GoudronViande24** [3kh0/slope#10]
In the game, it happens very often that the ball just goes through the floor or the jumps... and you die. Can you fix this?

**Comment by 3kh0** [comment]
> In the game, it happens very often that the ball just goes through the floor or the jumps... and you die. Can you fix this?

Try refreshing the page, this is a problem with the browser and it is something I can not fix. It would help me if you send me a screenshot of the whole screen so I could figure out if it is not just the browser! :)

**Comment by GoudronViande24** [comment]
I couldn't be fast enough to take a screenshot before dying, but I tried on many browsers and even incognito mode. They all have the problem.

**Comment by 3kh0** [comment]
> I couldn't be fast enough to take a screenshot before dying, but I tried on many browsers and even incognito mode. They all have the problem.

That is so weird! I will have to look through the code and test it myself. In the meantime if that happens again, a good old refresh will solve the problems until the strike back **:0**

**Comment by GoudronViande24** [comment]
I have question (not linked with this issue btw):
Have you copied the code from Y8 or rewritten the entire game yourself?

**Comment by 3kh0** [comment]
> I have question (not linked with this issue btw): Have you copied the code from Y8 or rewritten the entire game yourself?

Since the original game code did not run well on the Github pages servers, I have to rebuild the deployment and modify many things. So this is a heavily modified version of the original game made by Y8

**Comment by 3kh0** [comment]
Also, can I join your organization, Artivain?

**Comment by GoudronViande24** [comment]
hmm I don't know, the Artivain project is mostly a french-speaking team, if you still want to join though I can check this out with my partners

**Comment by 3kh0** [comment]
> hmm I don't know, the Artivain project is mostly a french-speaking team, if you still want to join though I can check this out with my partners

ok! :)

**Comment by GoudronViande24** [comment]
Send me a friend request on discord: GoudronViande24#7211

**Comment by 3kh0** [comment]
ok, i will do that when I get home :)
