### ISSUE TITLE
Game no longer works

### ISSUE THREAD

**Issue by nuggetofwisdom** [3kh0/slope#11]

**Comment by 3kh0** [comment]
Can you include a screenshot of the issue?

**Comment by nuggetofwisdom** [comment]
> Can you include a screenshot of the issue?

@3kh0
![Screenshot 2021-11-30 131121](https://user-images.githubusercontent.com/75330208/144103952-6a1d1840-230b-4aa6-a6ad-eef48d095d38.png)

**Comment by 3kh0** [comment]
> > Can you include a screenshot of the issue?
> 
> @3kh0 ![Screenshot 2021-11-30 131121](https://user-images.githubusercontent.com/75330208/144103952-6a1d1840-230b-4aa6-a6ad-eef48d095d38.png)

What browser are you using? It works for me. 🤔

**Comment by nuggetofwisdom** [comment]
> > > Can you include a screenshot of the issue?
> > 
> > 
> > @3kh0 ![Screenshot 2021-11-30 131121](https://user-images.githubusercontent.com/75330208/144103952-6a1d1840-230b-4aa6-a6ad-eef48d095d38.png)
> 
> What browser are you using? It works for me. 🤔

Huh. It must have been the school wifi because it works now that I'm at home.
