### ISSUE TITLE
Game no longer works

### ISSUE THREAD

**Issue by ItCameFr0mMars** [3kh0/slope#12]
When you click on the play, it takes you to [this site](https://sites.google.com/view/theadvancedmethod/home/changelog?authuser=0#h.m0jq3x6ztvw4)

**Comment by 3kh0** [comment]
> When you click on the play, it takes you to [this site](https://sites.google.com/view/theadvancedmethod/home/changelog?authuser=0#h.m0jq3x6ztvw4)

i know, i am working on it

**Comment by ItCameFr0mMars** [comment]
alright, thank you!
