### ISSUE TITLE
Pull request

### ISSUE THREAD

**Issue by Rockpods** [3kh0/slope#2]
I made some general improvements and some huge improvements for hosting

1. Blocked Ads
2. Made it much easier to deploy
3. Fixed bug where if you were to deploy in a folder called anything but slope it would not deploy
4. Made favicon local so it will still show up if the favicon hosting site is blocked
5. Fixed Credits

You can preview the site at https://slope-4.rockpodsinc.repl.co/ or https://rockpods.github.io/slope/index.html

**Comment by Rockpods** [comment]
Can you accept the pull request

**Comment by 3kh0** [comment]
done <3
